services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: mos_hack
      POSTGRES_PASSWORD: hackme12345
      POSTGRES_DB: mos_hack
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    # env_file:
      # - .env

volumes:
  postgres_data: